In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv(r"C:\IT\github\redbus_scraping_filtering\csv_files\final_backup\final_data.csv")

In [3]:
df1

,Unnamed: 0,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,Origin,Destination
0,0,IntrCity SmartBus,Scania AC Multi Axle Sleeper (2+1),23:59,06:30,06h 31m,671.0,32 Seats available,4.8,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
1,1,IntrCity SmartBus,A/C Seater / Sleeper (2+1),23:50,05:35,05h 45m,384.0,42 Seats available,4.6,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
2,2,FRESHBUS,Electric A/C Seater (2+2),11:00,17:40,06h 40m,450.0,38 Seats available,4.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
3,3,AdSri Sanvi Tours and Travels,A/C Sleeper (2+1),23:00,04:53,05h 53m,539.0,27 Seats available,4.5,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
4,4,FRESHBUS,Electric A/C Seater (2+2),23:40,05:55,06h 15m,450.0,38 Seats available,4.6,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16286,16286,Baikuntha Transport Service,Bharat Benz A/C Sleeper (2+1),19:30,01:00,05h 30m,540.0,50 Seats available,3.9,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16287,16287,Purple Wings Coaches,A/C Seater / Sleeper (2+1),19:55,01:15,05h 20m,601.0,42 Seats available,3.4,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16288,16288,Shree Ram Travels,Bharat Benz A/C Seater /Sleeper (2+1),20:45,01:40,04h 55m,530.0,32 Seats available,4.8,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16289,16289,Christina Travels,NON A/C Seater (2+2),08:20,12:15,03h 55m,650.0,45 Seats available,2.8,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16290,16290,Maa Laxmi,NON A/C Seater Push Back (2+1),18:30,23:15,04h 45m,500.0,36 Seats available,2.8,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat

In [4]:
del df1['Unnamed: 0']

In [5]:
df1

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,Origin,Destination
0,IntrCity SmartBus,Scania AC Multi Axle Sleeper (2+1),23:59,06:30,06h 31m,671.0,32 Seats available,4.8,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
1,IntrCity SmartBus,A/C Seater / Sleeper (2+1),23:50,05:35,05h 45m,384.0,42 Seats available,4.6,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
2,FRESHBUS,Electric A/C Seater (2+2),11:00,17:40,06h 40m,450.0,38 Seats available,4.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
3,AdSri Sanvi Tours and Travels,A/C Sleeper (2+1),23:00,04:53,05h 53m,539.0,27 Seats available,4.5,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
4,FRESHBUS,Electric A/C Seater (2+2),23:40,05:55,06h 15m,450.0,38 Seats available,4.6,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
...,...,...,...,...,...,...,...,...,...,...,...,...
16286,Baikuntha Transport Service,Bharat Benz A/C Sleeper (2+1),19:30,01:00,05h 30m,540.0,50 Seats available,3.9,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16287,Purple Wings Coaches,A/C Seater / Sleeper (2+1),19:55,01:15,05h 20m,601.0,42 Seats available,3.4,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16288,Shree Ram Travels,Bharat Benz A/C Seater /Sleeper (2+1),20:45,01:40,04h 55m,530.0,32 Seats available,4.8,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16289,Christina Travels,NON A/C Seater (2+2),08:20,12:15,03h 55m,650.0,45 Seats available,2.8,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16290,Maa Laxmi,NON A/C Seater Push Back (2+1),18:30,23:15,04h 45m,500.0,36 Seats available,2.8,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat

In [7]:
df1.to_csv("final_bus_data.csv")

In [8]:
df1[['Origin','Destination']] = df1['Route_name'].str.split(" to ", expand=True)

In [9]:
origin = list(set(df1['Origin'].to_list()))
origin

['Amritsar',
 'Gohpur',
 'Visakhapatnam',
 'Anantapur (andhra pradesh)',
 'Ghumarwin',
 'Jorhat',
 'Jhargram',
 'Manali',
 'Guntur (Andhra Pradesh)',
 'Thrissur',
 'Kozhikode',
 'Chennai',
 'Mysore',
 'Sikar',
 'Dinanagar (punjab)',
 'Madanapalli',
 'Ongole',
 'Khammam',
 'Chittoor (Andhra Pradesh)',
 'Muzaffarpur (Bihar)',
 'Durgapur (West Bengal)',
 'Narnaul',
 'Dalhousie',
 'Amalapuram',
 'Haflong',
 'Ernakulam',
 'Hisar (Haryana)',
 'Narasaraopet',
 'Thiruvananthapuram',
 'Kothagudem',
 'Rishikesh',
 'Tinsukia',
 'Shimla',
 'Hyderabad',
 'Hamirpur (Himachal Pradesh)',
 'Delhi',
 'Haridwar',
 'Kolkata',
 'Siliguri',
 'Kodad',
 'Bangalore',
 'Kota(Rajasthan)',
 'Kottayam',
 'Solan',
 'Rayachoti',
 'Kishangarh',
 'Bettiah',
 'Purnea',
 'Jodhpur',
 'Moran',
 'Pathankot',
 'Ludhiana',
 'Vrindavan',
 'Jaipur (Rajasthan)',
 'Agra',
 'Kadiri',
 'Motihari',
 'Digha',
 'Pali (Rajasthan)',
 'Macherla (andhra pradesh)',
 'Goalpara',
 'Eluru',
 'Sujanpur (himachal pradesh)',
 'Chandigarh',
 'Jammu (j and k)',
 'Darbhanga',
 'Tezpur',
 'Katra (jammu and kashmir)',
 'North Lakhimpur',
 'Bikaner',
 'Jagityal',
 'Bokakhat',
 'Baddi (Himachal Pradesh)',
 'Palampur',
 'Lucknow',
 'Haldia',
 'Patna (Bihar)',
 'Dharamshala (Himachal Pradesh)',
 'Yamuna Nagar',
 'Vinukonda',
 'Rajahmundry',
 'Purulia',
 'Gopalganj (Bihar)',
 'Udaipur',
 'Vijayawada',
 'Kangra',
 'Dhekiajuli',
 'Talwara',
 'Ranchi',
 'Kannur',
 'Beawar (Rajasthan)',
 'Nagaon (Assam)',
 'Coimbatore',
 'Hazaribagh',
 'Jawala Ji',
 'Nellore',
 'Sibsagar',
 'Silchar',
 'Guwahati',
 'Burdwan',
 'Midnapore',
 'Karimnagar',
 'Dibrugarh',
 'Godavarikhani',
 'Suri',
 'Balmiki Nagar (bihar)',
 'Biswanath Charali',
 'Barasat (West Bengal)',
 'Kullu',
 'Bolpur (West Bengal)',
 'Kalpetta (kerala)',
 'Dehradun',
 'Kakinada',
 'Dhemaji',
 'Tirupati',
 'Chamba (Himachal Pradesh)',
 'Kadapa',
 'Asansol (West Bengal)',
 'Rohtak',
 'Berhampore (West Bengal)',
 'Habra',
 'Kurnool',
 'Dhubri',
 'Aligarh (uttar pradesh)']

In [10]:
destination = list(set(df1['Destination'].to_list()))
destination

['Amritsar',
 'Visakhapatnam',
 'Anantapur (andhra pradesh)',
 'Jorhat',
 'Bajkul (West Bengal)',
 'Manali',
 'Thrissur',
 'Kozhikode',
 'Chennai',
 'Mysore',
 'Sikar',
 'Dinanagar (punjab)',
 'Madanapalli',
 'Forbesganj',
 'Ongole',
 'Chittoor (Andhra Pradesh)',
 'Nalagarh',
 'Mechogram',
 'Muzaffarpur (Bihar)',
 'Durgapur (West Bengal)',
 'Dalhousie',
 'Amalapuram',
 'Haflong',
 'Ernakulam',
 'Sarkaghat',
 'Hisar (Haryana)',
 'Narasaraopet',
 'Thiruvananthapuram',
 'Katihar',
 'Kothagudem',
 'Rishikesh',
 'Tinsukia',
 'Araria (Bihar)',
 'Malda',
 'Shimla',
 'Pilani',
 'Hyderabad',
 'Hamirpur (Himachal Pradesh)',
 'Delhi',
 'Warangal',
 'Haridwar',
 'Kolkata',
 'Siliguri',
 'Kolaghat',
 'Bangalore',
 'Kota(Rajasthan)',
 'Kottayam',
 'Solan',
 'Rayachoti',
 'Bettiah',
 'Purnea',
 'Jodhpur',
 'Heria',
 'Pathankot',
 'Vrindavan',
 'Ludhiana',
 'Moran',
 'Contai (Kanthi)',
 'Jaipur (Rajasthan)',
 'Agra',
 'Bhilwara',
 'Kadiri',
 'Motihari',
 'Bharatpur',
 'Digha',
 'Pali (Rajasthan)',
 'Bankura',
 'Baijnath',
 'Sujanpur (himachal pradesh)',
 'Hajipur (Bihar)',
 'Chandigarh',
 'Jammu (j and k)',
 'Tezpur',
 'Una (Himachal Pradesh)',
 'Katra (jammu and kashmir)',
 'Nimtouri',
 'Futishanko',
 'North Lakhimpur',
 'Bikaner',
 'Ajmer',
 'Bokakhat',
 'Baddi (Himachal Pradesh)',
 'Palampur',
 'Lucknow',
 'Haldia',
 'Patna (Bihar)',
 'Dharamshala (Himachal Pradesh)',
 'Yamuna Nagar',
 'Kirnahar (West Bengal)',
 'Debra',
 'Kathgodam',
 'Rajahmundry',
 'Purulia',
 'Gopalganj (Bihar)',
 'Janakpur (Nepal)',
 'Udaipur',
 'Vijayawada',
 'Kangra',
 'Talwara',
 'Ranchi',
 'Kannur',
 'Beawar (Rajasthan)',
 'Nagaon (Assam)',
 'Hazaribagh',
 'Jawala Ji',
 'Sibsagar',
 'Silchar',
 'Bhadrachalam',
 'Sathupally',
 'Guwahati',
 'Srisailam',
 'Ramnagar (West Bengal)',
 'Burdwan',
 'Midnapore',
 'Karimnagar',
 'Chandipur (West Bengal)',
 'Dibrugarh',
 'Godavarikhani',
 'Arambagh (West Bengal)',
 'Suri',
 'Balmiki Nagar (bihar)',
 'Biswanath Charali',
 'Barasat (West Bengal)',
 'Kullu',
 'Bolpur (West Bengal)',
 'Kalpetta (kerala)',
 'Dehradun',
 'Saharsa',
 'Haldwani',
 'Ooty',
 'Golaghat',
 'Kakinada',
 'Nandakumar (west bengal)',
 'Raxaul',
 'Tirupati',
 'Chamba (Himachal Pradesh)',
 'Kadapa',
 'Asansol (West Bengal)',
 'Mecheda (West Bengal)',
 'Reckong Peo (Himachal Pradesh)',
 'Mathura',
 'Rohtak',
 'Berhampore (West Bengal)',
 'Habra',
 'Adilabad',
 'Kurnool',
 'Armoor',
 'Dhubri',
 'Bakkhali',
 'Mancherial',
 'Aligarh (uttar pradesh)',
 'Nirmal']

In [11]:
data = {
    "Origin": origin
}

In [12]:
origin_df = pd.DataFrame(data)
origin_df

                         Origin
0                      Amritsar
1                        Gohpur
2                 Visakhapatnam
3    Anantapur (andhra pradesh)
4                     Ghumarwin
..                          ...
119    Berhampore (West Bengal)
120                       Habra
121                     Kurnool
122                      Dhubri
123     Aligarh (uttar pradesh)

[124 rows x 1 columns]

In [13]:
origin_df.to_csv("origin.csv", index= False)

In [14]:
data = {
    "destination": destination
}

In [15]:
destination_df = pd.DataFrame(data)
destination_df

                    destination
0                      Amritsar
1                 Visakhapatnam
2    Anantapur (andhra pradesh)
3                        Jorhat
4          Bajkul (West Bengal)
..                          ...
147                      Dhubri
148                    Bakkhali
149                  Mancherial
150     Aligarh (uttar pradesh)
151                      Nirmal

[152 rows x 1 columns]

In [16]:
destination_df.to_csv("destination.csv", index= False)