In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv(r"C:\IT\github\redbus_scraping_filtering\csv_files\final_backup\final_data.csv")

In [3]:
df1

,Unnamed: 0,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,Origin,Destination
0,0,IntrCity SmartBus,Scania AC Multi Axle Sleeper (2+1),23:59,06:30,06h 31m,671.0,32 Seats available,4.8,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
1,1,IntrCity SmartBus,A/C Seater / Sleeper (2+1),23:50,05:35,05h 45m,384.0,42 Seats available,4.6,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
2,2,FRESHBUS,Electric A/C Seater (2+2),11:00,17:40,06h 40m,450.0,38 Seats available,4.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
3,3,AdSri Sanvi Tours and Travels,A/C Sleeper (2+1),23:00,04:53,05h 53m,539.0,27 Seats available,4.5,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
4,4,FRESHBUS,Electric A/C Seater (2+2),23:40,05:55,06h 15m,450.0,38 Seats available,4.6,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16286,16286,Baikuntha Transport Service,Bharat Benz A/C Sleeper (2+1),19:30,01:00,05h 30m,540.0,50 Seats available,3.9,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16287,16287,Purple Wings Coaches,A/C Seater / Sleeper (2+1),19:55,01:15,05h 20m,601.0,42 Seats available,3.4,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16288,16288,Shree Ram Travels,Bharat Benz A/C Seater /Sleeper (2+1),20:45,01:40,04h 55m,530.0,32 Seats available,4.8,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16289,16289,Christina Travels,NON A/C Seater (2+2),08:20,12:15,03h 55m,650.0,45 Seats available,2.8,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16290,16290,Maa Laxmi,NON A/C Seater Push Back (2+1),18:30,23:15,04h 45m,500.0,36 Seats available,2.8,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat

In [6]:
del df1['Unnamed: 0']

In [7]:
df1

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,Origin,Destination
0,IntrCity SmartBus,Scania AC Multi Axle Sleeper (2+1),23:59,06:30,06h 31m,671.0,32 Seats available,4.8,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
1,IntrCity SmartBus,A/C Seater / Sleeper (2+1),23:50,05:35,05h 45m,384.0,42 Seats available,4.6,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
2,FRESHBUS,Electric A/C Seater (2+2),11:00,17:40,06h 40m,450.0,38 Seats available,4.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
3,AdSri Sanvi Tours and Travels,A/C Sleeper (2+1),23:00,04:53,05h 53m,539.0,27 Seats available,4.5,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
4,FRESHBUS,Electric A/C Seater (2+2),23:40,05:55,06h 15m,450.0,38 Seats available,4.6,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
...,...,...,...,...,...,...,...,...,...,...,...,...
16286,Baikuntha Transport Service,Bharat Benz A/C Sleeper (2+1),19:30,01:00,05h 30m,540.0,50 Seats available,3.9,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16287,Purple Wings Coaches,A/C Seater / Sleeper (2+1),19:55,01:15,05h 20m,601.0,42 Seats available,3.4,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16288,Shree Ram Travels,Bharat Benz A/C Seater /Sleeper (2+1),20:45,01:40,04h 55m,530.0,32 Seats available,4.8,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16289,Christina Travels,NON A/C Seater (2+2),08:20,12:15,03h 55m,650.0,45 Seats available,2.8,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16290,Maa Laxmi,NON A/C Seater Push Back (2+1),18:30,23:15,04h 45m,500.0,36 Seats available,2.8,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat

In [8]:
df1.to_csv("final_data.csv")

In [9]:
df1[['Origin','Destination']] = df1['Route_name'].str.split(" to ", expand=True)

In [10]:
origin = list(set(df1['Origin'].to_list()))
origin

['Kurnool',
 'Thiruvananthapuram',
 'Purulia',
 'Vrindavan',
 'Kothagudem',
 'Bikaner',
 'Dhubri',
 'Dhekiajuli',
 'Dinanagar (punjab)',
 'Gohpur',
 'Chittoor (Andhra Pradesh)',
 'Nagaon (Assam)',
 'Madanapalli',
 'Kangra',
 'Jhargram',
 'Kota(Rajasthan)',
 'Goalpara',
 'Ranchi',
 'Durgapur (West Bengal)',
 'Vijayawada',
 'Hazaribagh',
 'Muzaffarpur (Bihar)',
 'Bettiah',
 'Pathankot',
 'Biswanath Charali',
 'Chandigarh',
 'Berhampore (West Bengal)',
 'Guntur (Andhra Pradesh)',
 'Kalpetta (kerala)',
 'Haridwar',
 'Purnea',
 'Moran',
 'Eluru',
 'North Lakhimpur',
 'Hisar (Haryana)',
 'Manali',
 'Kishangarh',
 'Bokakhat',
 'Jagityal',
 'Rayachoti',
 'Coimbatore',
 'Habra',
 'Delhi',
 'Anantapur (andhra pradesh)',
 'Ongole',
 'Balmiki Nagar (bihar)',
 'Lucknow',
 'Jorhat',
 'Sikar',
 'Talwara',
 'Kozhikode',
 'Tinsukia',
 'Udaipur',
 'Motihari',
 'Burdwan',
 'Digha',
 'Jawala Ji',
 'Vinukonda',
 'Ghumarwin',
 'Narnaul',
 'Rajahmundry',
 'Rishikesh',
 'Kolkata',
 'Godavarikhani',
 'Shimla',
 'Khammam',
 'Thrissur',
 'Patna (Bihar)',
 'Karimnagar',
 'Kadiri',
 'Kodad',
 'Darbhanga',
 'Sujanpur (himachal pradesh)',
 'Macherla (andhra pradesh)',
 'Visakhapatnam',
 'Ludhiana',
 'Kakinada',
 'Barasat (West Bengal)',
 'Bolpur (West Bengal)',
 'Ernakulam',
 'Hamirpur (Himachal Pradesh)',
 'Chennai',
 'Dehradun',
 'Solan',
 'Chamba (Himachal Pradesh)',
 'Tezpur',
 'Jammu (j and k)',
 'Kullu',
 'Kannur',
 'Jodhpur',
 'Amritsar',
 'Guwahati',
 'Mysore',
 'Haldia',
 'Haflong',
 'Amalapuram',
 'Bangalore',
 'Kottayam',
 'Rohtak',
 'Midnapore',
 'Tirupati',
 'Dhemaji',
 'Asansol (West Bengal)',
 'Baddi (Himachal Pradesh)',
 'Dharamshala (Himachal Pradesh)',
 'Hyderabad',
 'Aligarh (uttar pradesh)',
 'Beawar (Rajasthan)',
 'Yamuna Nagar',
 'Pali (Rajasthan)',
 'Narasaraopet',
 'Dibrugarh',
 'Palampur',
 'Suri',
 'Kadapa',
 'Sibsagar',
 'Silchar',
 'Jaipur (Rajasthan)',
 'Nellore',
 'Agra',
 'Katra (jammu and kashmir)',
 'Gopalganj (Bihar)',
 'Dalhousie',
 'Siliguri']

In [11]:
destination = list(set(df1['Destination'].to_list()))
destination

['Kurnool',
 'Srisailam',
 'Thiruvananthapuram',
 'Purulia',
 'Vrindavan',
 'Kothagudem',
 'Bikaner',
 'Dhubri',
 'Dinanagar (punjab)',
 'Forbesganj',
 'Araria (Bihar)',
 'Arambagh (West Bengal)',
 'Chittoor (Andhra Pradesh)',
 'Reckong Peo (Himachal Pradesh)',
 'Nagaon (Assam)',
 'Madanapalli',
 'Kangra',
 'Nandakumar (west bengal)',
 'Kota(Rajasthan)',
 'Futishanko',
 'Kathgodam',
 'Ranchi',
 'Durgapur (West Bengal)',
 'Vijayawada',
 'Hazaribagh',
 'Muzaffarpur (Bihar)',
 'Bettiah',
 'Pathankot',
 'Raxaul',
 'Biswanath Charali',
 'Chandigarh',
 'Berhampore (West Bengal)',
 'Nirmal',
 'Bhadrachalam',
 'Kalpetta (kerala)',
 'Haridwar',
 'Baijnath',
 'Purnea',
 'Moran',
 'Janakpur (Nepal)',
 'Hisar (Haryana)',
 'Manali',
 'North Lakhimpur',
 'Heria',
 'Bokakhat',
 'Chandipur (West Bengal)',
 'Rayachoti',
 'Kirnahar (West Bengal)',
 'Habra',
 'Delhi',
 'Anantapur (andhra pradesh)',
 'Ongole',
 'Balmiki Nagar (bihar)',
 'Lucknow',
 'Haldwani',
 'Jorhat',
 'Malda',
 'Sikar',
 'Talwara',
 'Kozhikode',
 'Tinsukia',
 'Udaipur',
 'Motihari',
 'Saharsa',
 'Burdwan',
 'Digha',
 'Jawala Ji',
 'Bankura',
 'Sarkaghat',
 'Mancherial',
 'Rajahmundry',
 'Rishikesh',
 'Kolkata',
 'Contai (Kanthi)',
 'Godavarikhani',
 'Shimla',
 'Thrissur',
 'Bharatpur',
 'Mecheda (West Bengal)',
 'Ramnagar (West Bengal)',
 'Patna (Bihar)',
 'Karimnagar',
 'Kadiri',
 'Adilabad',
 'Bajkul (West Bengal)',
 'Sujanpur (himachal pradesh)',
 'Visakhapatnam',
 'Ajmer',
 'Ludhiana',
 'Kakinada',
 'Hajipur (Bihar)',
 'Warangal',
 'Mathura',
 'Barasat (West Bengal)',
 'Bolpur (West Bengal)',
 'Una (Himachal Pradesh)',
 'Ernakulam',
 'Hamirpur (Himachal Pradesh)',
 'Chennai',
 'Dehradun',
 'Solan',
 'Chamba (Himachal Pradesh)',
 'Tezpur',
 'Jammu (j and k)',
 'Kullu',
 'Bhilwara',
 'Kannur',
 'Jodhpur',
 'Amritsar',
 'Guwahati',
 'Mysore',
 'Haldia',
 'Haflong',
 'Pilani',
 'Amalapuram',
 'Bakkhali',
 'Bangalore',
 'Kottayam',
 'Katihar',
 'Rohtak',
 'Midnapore',
 'Tirupati',
 'Sathupally',
 'Asansol (West Bengal)',
 'Baddi (Himachal Pradesh)',
 'Ooty',
 'Dharamshala (Himachal Pradesh)',
 'Hyderabad',
 'Aligarh (uttar pradesh)',
 'Nalagarh',
 'Beawar (Rajasthan)',
 'Yamuna Nagar',
 'Pali (Rajasthan)',
 'Narasaraopet',
 'Kolaghat',
 'Dibrugarh',
 'Palampur',
 'Suri',
 'Debra',
 'Kadapa',
 'Sibsagar',
 'Silchar',
 'Jaipur (Rajasthan)',
 'Golaghat',
 'Agra',
 'Katra (jammu and kashmir)',
 'Gopalganj (Bihar)',
 'Mechogram',
 'Dalhousie',
 'Nimtouri',
 'Armoor',
 'Siliguri']

In [12]:
data = {
    "Origin": origin
}

In [13]:
origin_df = pd.DataFrame(data)
origin_df

                        Origin
0                      Kurnool
1           Thiruvananthapuram
2                      Purulia
3                    Vrindavan
4                   Kothagudem
..                         ...
119                       Agra
120  Katra (jammu and kashmir)
121          Gopalganj (Bihar)
122                  Dalhousie
123                   Siliguri

[124 rows x 1 columns]

In [15]:
origin_df.to_csv("origin.csv", index= False)

In [16]:
data = {
    "destination": destination
}

In [17]:
destination_df = pd.DataFrame(data)
destination_df

            destination
0               Kurnool
1             Srisailam
2    Thiruvananthapuram
3               Purulia
4             Vrindavan
..                  ...
147           Mechogram
148           Dalhousie
149            Nimtouri
150              Armoor
151            Siliguri

[152 rows x 1 columns]

In [18]:
destination_df.to_csv("destination.csv", index= False)