In [3]:
import pandas as pd

In [6]:
df1 = pd.read_csv(r"C:\IT\github\redbus_scraping_filtering\csv_files\final_backup\final_data.csv")

In [7]:
df1

,Unnamed: 0,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,Origin,Destination
0,0,IntrCity SmartBus,Scania AC Multi Axle Sleeper (2+1),23:59,06:30,06h 31m,671.0,32 Seats available,4.8,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
1,1,IntrCity SmartBus,A/C Seater / Sleeper (2+1),23:50,05:35,05h 45m,384.0,42 Seats available,4.6,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
2,2,FRESHBUS,Electric A/C Seater (2+2),11:00,17:40,06h 40m,450.0,38 Seats available,4.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
3,3,AdSri Sanvi Tours and Travels,A/C Sleeper (2+1),23:00,04:53,05h 53m,539.0,27 Seats available,4.5,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
4,4,FRESHBUS,Electric A/C Seater (2+2),23:40,05:55,06h 15m,450.0,38 Seats available,4.6,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16286,16286,Baikuntha Transport Service,Bharat Benz A/C Sleeper (2+1),19:30,01:00,05h 30m,540.0,50 Seats available,3.9,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16287,16287,Purple Wings Coaches,A/C Seater / Sleeper (2+1),19:55,01:15,05h 20m,601.0,42 Seats available,3.4,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16288,16288,Shree Ram Travels,Bharat Benz A/C Seater /Sleeper (2+1),20:45,01:40,04h 55m,530.0,32 Seats available,4.8,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16289,16289,Christina Travels,NON A/C Seater (2+2),08:20,12:15,03h 55m,650.0,45 Seats available,2.8,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16290,16290,Maa Laxmi,NON A/C Seater Push Back (2+1),18:30,23:15,04h 45m,500.0,36 Seats available,2.8,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat

In [8]:
del df1['Unnamed: 0']

In [9]:
df1

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,Origin,Destination
0,IntrCity SmartBus,Scania AC Multi Axle Sleeper (2+1),23:59,06:30,06h 31m,671.0,32 Seats available,4.8,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
1,IntrCity SmartBus,A/C Seater / Sleeper (2+1),23:50,05:35,05h 45m,384.0,42 Seats available,4.6,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
2,FRESHBUS,Electric A/C Seater (2+2),11:00,17:40,06h 40m,450.0,38 Seats available,4.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
3,AdSri Sanvi Tours and Travels,A/C Sleeper (2+1),23:00,04:53,05h 53m,539.0,27 Seats available,4.5,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
4,FRESHBUS,Electric A/C Seater (2+2),23:40,05:55,06h 15m,450.0,38 Seats available,4.6,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Hyderabad,Vijayawada
...,...,...,...,...,...,...,...,...,...,...,...,...
16286,Baikuntha Transport Service,Bharat Benz A/C Sleeper (2+1),19:30,01:00,05h 30m,540.0,50 Seats available,3.9,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16287,Purple Wings Coaches,A/C Seater / Sleeper (2+1),19:55,01:15,05h 20m,601.0,42 Seats available,3.4,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16288,Shree Ram Travels,Bharat Benz A/C Seater /Sleeper (2+1),20:45,01:40,04h 55m,530.0,32 Seats available,4.8,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16289,Christina Travels,NON A/C Seater (2+2),08:20,12:15,03h 55m,650.0,45 Seats available,2.8,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat
16290,Maa Laxmi,NON A/C Seater Push Back (2+1),18:30,23:15,04h 45m,500.0,36 Seats available,2.8,https://www.redbus.in/bus-tickets/dibrugarh-to...,Dibrugarh to Bokakhat,Dibrugarh,Bokakhat

In [10]:
df1[['Origin','Destination']] = df1['Route_name'].str.split(" to ", expand=True)

In [11]:
origin = list(set(df1['Origin'].to_list()))
origin

['Kadapa',
 'Kottayam',
 'Siliguri',
 'Dehradun',
 'Dalhousie',
 'Thiruvananthapuram',
 'Aligarh (uttar pradesh)',
 'Beawar (Rajasthan)',
 'Berhampore (West Bengal)',
 'Eluru',
 'Bettiah',
 'Tezpur',
 'Patna (Bihar)',
 'Kakinada',
 'Bangalore',
 'Dinanagar (punjab)',
 'Kodad',
 'Ludhiana',
 'Hisar (Haryana)',
 'Kangra',
 'Kothagudem',
 'Biswanath Charali',
 'Midnapore',
 'Delhi',
 'Sujanpur (himachal pradesh)',
 'Rajahmundry',
 'Haflong',
 'Kishangarh',
 'Jammu (j and k)',
 'Kadiri',
 'Ernakulam',
 'Motihari',
 'Narnaul',
 'Jorhat',
 'Rishikesh',
 'Coimbatore',
 'Baddi (Himachal Pradesh)',
 'Haldia',
 'Muzaffarpur (Bihar)',
 'Shimla',
 'Darbhanga',
 'Hyderabad',
 'Visakhapatnam',
 'Jagityal',
 'Palampur',
 'Anantapur (andhra pradesh)',
 'Kozhikode',
 'Burdwan',
 'Talwara',
 'Chittoor (Andhra Pradesh)',
 'Kota(Rajasthan)',
 'Asansol (West Bengal)',
 'Kurnool',
 'Chandigarh',
 'Sibsagar',
 'Dhemaji',
 'Manali',
 'Dhubri',
 'Bolpur (West Bengal)',
 'Purnea',
 'Guwahati',
 'Karimnagar',
 'Agra',
 'Godavarikhani',
 'Kalpetta (kerala)',
 'Dharamshala (Himachal Pradesh)',
 'Digha',
 'North Lakhimpur',
 'Hamirpur (Himachal Pradesh)',
 'Kullu',
 'Ghumarwin',
 'Nellore',
 'Amritsar',
 'Bikaner',
 'Guntur (Andhra Pradesh)',
 'Mysore',
 'Ongole',
 'Lucknow',
 'Madanapalli',
 'Kolkata',
 'Silchar',
 'Vinukonda',
 'Durgapur (West Bengal)',
 'Barasat (West Bengal)',
 'Pali (Rajasthan)',
 'Purulia',
 'Tinsukia',
 'Thrissur',
 'Amalapuram',
 'Jodhpur',
 'Yamuna Nagar',
 'Gopalganj (Bihar)',
 'Rayachoti',
 'Balmiki Nagar (bihar)',
 'Vijayawada',
 'Nagaon (Assam)',
 'Pathankot',
 'Vrindavan',
 'Rohtak',
 'Gohpur',
 'Jaipur (Rajasthan)',
 'Jawala Ji',
 'Ranchi',
 'Moran',
 'Chamba (Himachal Pradesh)',
 'Chennai',
 'Jhargram',
 'Khammam',
 'Katra (jammu and kashmir)',
 'Narasaraopet',
 'Macherla (andhra pradesh)',
 'Sikar',
 'Bokakhat',
 'Dhekiajuli',
 'Udaipur',
 'Suri',
 'Goalpara',
 'Hazaribagh',
 'Haridwar',
 'Solan',
 'Habra',
 'Dibrugarh',
 'Kannur',
 'Tirupati']

In [12]:
destination = list(set(df1['Destination'].to_list()))
destination

['Kadapa',
 'Kottayam',
 'Siliguri',
 'Dehradun',
 'Dalhousie',
 'Thiruvananthapuram',
 'Aligarh (uttar pradesh)',
 'Beawar (Rajasthan)',
 'Berhampore (West Bengal)',
 'Bettiah',
 'Tezpur',
 'Patna (Bihar)',
 'Kakinada',
 'Bangalore',
 'Dinanagar (punjab)',
 'Reckong Peo (Himachal Pradesh)',
 'Bhadrachalam',
 'Ludhiana',
 'Kangra',
 'Hisar (Haryana)',
 'Haldwani',
 'Kothagudem',
 'Mancherial',
 'Nirmal',
 'Futishanko',
 'Midnapore',
 'Debra',
 'Delhi',
 'Biswanath Charali',
 'Sujanpur (himachal pradesh)',
 'Rajahmundry',
 'Warangal',
 'Hajipur (Bihar)',
 'Haflong',
 'Jammu (j and k)',
 'Kadiri',
 'Pilani',
 'Ernakulam',
 'Bharatpur',
 'Motihari',
 'Jorhat',
 'Araria (Bihar)',
 'Rishikesh',
 'Baddi (Himachal Pradesh)',
 'Haldia',
 'Muzaffarpur (Bihar)',
 'Shimla',
 'Sarkaghat',
 'Hyderabad',
 'Visakhapatnam',
 'Palampur',
 'Anantapur (andhra pradesh)',
 'Kozhikode',
 'Armoor',
 'Burdwan',
 'Talwara',
 'Chittoor (Andhra Pradesh)',
 'Kota(Rajasthan)',
 'Sathupally',
 'Asansol (West Bengal)',
 'Kurnool',
 'Chandigarh',
 'Kathgodam',
 'Una (Himachal Pradesh)',
 'Manali',
 'Sibsagar',
 'Dhubri',
 'Golaghat',
 'Bajkul (West Bengal)',
 'Arambagh (West Bengal)',
 'Saharsa',
 'Bolpur (West Bengal)',
 'Contai (Kanthi)',
 'Katihar',
 'Purnea',
 'Kirnahar (West Bengal)',
 'Guwahati',
 'Karimnagar',
 'Agra',
 'Godavarikhani',
 'Kalpetta (kerala)',
 'Dharamshala (Himachal Pradesh)',
 'Digha',
 'North Lakhimpur',
 'Hamirpur (Himachal Pradesh)',
 'Kullu',
 'Amritsar',
 'Bikaner',
 'Ajmer',
 'Bhilwara',
 'Kolaghat',
 'Mysore',
 'Ongole',
 'Lucknow',
 'Baijnath',
 'Madanapalli',
 'Kolkata',
 'Silchar',
 'Durgapur (West Bengal)',
 'Ramnagar (West Bengal)',
 'Ooty',
 'Heria',
 'Barasat (West Bengal)',
 'Pali (Rajasthan)',
 'Purulia',
 'Tinsukia',
 'Forbesganj',
 'Nandakumar (west bengal)',
 'Thrissur',
 'Amalapuram',
 'Malda',
 'Srisailam',
 'Jodhpur',
 'Adilabad',
 'Yamuna Nagar',
 'Gopalganj (Bihar)',
 'Rayachoti',
 'Balmiki Nagar (bihar)',
 'Vijayawada',
 'Nagaon (Assam)',
 'Bankura',
 'Pathankot',
 'Vrindavan',
 'Rohtak',
 'Mechogram',
 'Raxaul',
 'Jaipur (Rajasthan)',
 'Jawala Ji',
 'Ranchi',
 'Moran',
 'Chamba (Himachal Pradesh)',
 'Nimtouri',
 'Chennai',
 'Janakpur (Nepal)',
 'Mathura',
 'Bakkhali',
 'Mecheda (West Bengal)',
 'Nalagarh',
 'Katra (jammu and kashmir)',
 'Narasaraopet',
 'Sikar',
 'Bokakhat',
 'Udaipur',
 'Suri',
 'Hazaribagh',
 'Chandipur (West Bengal)',
 'Haridwar',
 'Solan',
 'Habra',
 'Dibrugarh',
 'Kannur',
 'Tirupati']

In [13]:
data = {
    "Origin": origin
}

In [14]:
origin_df = pd.DataFrame(data)
origin_df

        Origin
0       Kadapa
1     Kottayam
2     Siliguri
3     Dehradun
4    Dalhousie
..         ...
119      Solan
120      Habra
121  Dibrugarh
122     Kannur
123   Tirupati

[124 rows x 1 columns]

In [16]:
origin_df.to_csv(r"C:\IT\github\redbus_scraping_filtering\csv_files\final_backup\origin.csv", index= False)

In [17]:
data = {
    "destination": destination
}

In [18]:
destination_df = pd.DataFrame(data)
destination_df

    destination
0        Kadapa
1      Kottayam
2      Siliguri
3      Dehradun
4     Dalhousie
..          ...
147       Solan
148       Habra
149   Dibrugarh
150      Kannur
151    Tirupati

[152 rows x 1 columns]

In [19]:
destination_df.to_csv(r"C:\IT\github\redbus_scraping_filtering\csv_files\final_backup\destination.csv", index= False)